#!/bin/bash
# ============================================================
# Venlix Nodes - Node Agent Installer
# Run on EACH machine that will host VMs (the "node"/slave).
#
#   sudo bash install-node.sh
#
# You will be prompted for:
#   - A unique name for this node
#   - The agent token (shared secret generated by the panel)
# ============================================================
set -e

AGENT_DIR="/opt/venlix-node"

echo ""
echo "============================================="
echo "  Venlix Nodes - Node Agent Installer"
echo "============================================="
echo ""

if [[ $EUID -ne 0 ]]; then
  echo "This must be run as root (use sudo)." >&2
  exit 1
fi

# ---------- prompt ----------
read -p "Node name (e.g. Node-2-Mumbai): " NODE_NAME
NODE_NAME="${NODE_NAME:-Node}"
read -p "Agent token (from panel -> Nodes -> Create Node): " AGENT_TOKEN
if [[ -z "$AGENT_TOKEN" ]]; then
  echo "Agent token is required." >&2
  exit 1
fi

# ---------- system deps (QEMU stack) ----------
echo "[+] Updating packages..."
apt-get update -y -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  qemu-system-x86 qemu-utils cloud-image-utils cloud-init \
  wget curl openssl python3 nodejs npm \
  >/dev/null 2>&1 || true

# ---------- Node.js runtime check ----------
if ! command -v node >/dev/null 2>&1; then
  echo "[!] Node.js not found; installing Node 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1
  apt-get install -y -qq nodejs >/dev/null 2>&1
fi

# ---------- copy agent ----------
echo "[+] Installing agent to $AGENT_DIR"
mkdir -p "$AGENT_DIR"
if [[ -d ./node-agent ]]; then
  cp -r ./node-agent/. "$AGENT_DIR/"
elif [[ -f agent.js ]]; then
  cp -r . "$AGENT_DIR/"
else
  echo "[x] Could not find the node-agent files. Run this script from the venlix-nodes repo root." >&2
  exit 1
fi

# ---------- write env ----------
AGENT_UPDATE_REPO="${AGENT_UPDATE_REPO:-https://github.com/rgdevil54321-afk/vm-panel-.git}"
AGENT_UPDATE_BRANCH="${AGENT_UPDATE_BRANCH:-main}"
cat > "$AGENT_DIR/.env" <<EOF
AGENT_PORT=3005
AGENT_HOST=0.0.0.0
AGENT_TOKEN=$AGENT_TOKEN
AGENT_UPDATE_REPO=$AGENT_UPDATE_REPO
AGENT_UPDATE_BRANCH=$AGENT_UPDATE_BRANCH
NO_KVM=
EOF

# Create state + vm dirs
mkdir -p "$AGENT_DIR/data" "$AGENT_DIR/vms"

echo "[+] Installing Node dependencies (uuid only)..."
cd "$AGENT_DIR"
# uuid is the only third-party dependency (no native build)
npm install uuid --save
if [[ ! -d node_modules ]]; then
  echo "[x] npm install failed. Check network access." >&2
  exit 1
fi

# ---------- set node metadata ----------
cat > /tmp/venlix-meta.json <<EOF
{"name":"$NODE_NAME"}
EOF
AGENT_TOKEN="$AGENT_TOKEN" node -e "require('dotenv')" 2>/dev/null || true
# simplest: store name via env on first boot; agent reads AGENT_NODE_NAME
echo "AGENT_NODE_NAME=$NODE_NAME" >> "$AGENT_DIR/.env"

# ---------- systemd unit ----------
echo "[+] Creating systemd service..."
cat > /etc/systemd/system/venlix-node.service <<EOF
[Unit]
Description=Venlix Nodes - Node Agent (QEMU VM Hypervisor)
After=network.target

[Service]
Type=simple
WorkingDirectory=$AGENT_DIR
EnvironmentFile=$AGENT_DIR/.env
ExecStart=/usr/bin/node $AGENT_DIR/agent.js
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable venlix-node
systemctl restart venlix-node || true

echo ""
echo "============================================="
echo "  Node agent installed."
echo ""
echo "  Name   : $NODE_NAME"
echo "  Port   : 3005 (open TCP in firewall)"
echo "  Token  : $AGENT_TOKEN"
echo ""
echo "  Next steps on the panel:"
echo "    1. Nodes -> Create Node"
echo "       Host = <this server's IP>, Port = 3005"
echo "       Agent Token = $AGENT_TOKEN"
echo "    2. If the node shows 'QEMU missing' it means the"
echo "       prerequisites failed to install; run them manually."
echo "============================================="
