#!/bin/bash
# ============================================================
# Venlix Nodes - Node Agent Installer
# Run on EACH machine that will host VMs (the "node"/slave).
#
#   sudo bash install-node.sh
#
# You will be prompted for:
#   - A unique name for this node
#   - The agent token (shared secret generated by the panel)
# ============================================================
set -e

AGENT_DIR="/opt/venlix-node"

echo ""
echo "============================================="
echo "  Venlix Nodes - Node Agent Installer"
echo "============================================="
echo ""

if [[ $EUID -ne 0 ]]; then
  echo "This must be run as root (use sudo)." >&2
  exit 1
fi

# ---------- prompt ----------
read -p "Node name (e.g. Node-2-Mumbai): " NODE_NAME
NODE_NAME="${NODE_NAME:-Node}"
read -p "Agent token (from panel -> Nodes -> Create Node): " AGENT_TOKEN
if [[ -z "$AGENT_TOKEN" ]]; then
  echo "Agent token is required." >&2
  exit 1
fi

# ---------- system deps (QEMU stack) ----------
echo "[+] Updating packages..."
apt-get update -y -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  qemu-system-x86 qemu-utils cloud-image-utils cloud-init \
  wget curl openssl python3 nodejs npm \
  >/dev/null 2>&1 || true

# ---------- Node.js runtime check ----------
if ! command -v node >/dev/null 2>&1; then
  echo "[!] Node.js not found; installing Node 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - >/dev/null 2>&1
  apt-get install -y -qq nodejs >/dev/null 2>&1
fi

# ---------- copy agent ----------
echo "[+] Installing agent to $AGENT_DIR"
mkdir -p "$AGENT_DIR"
if [[ -d ./node-agent ]]; then
  cp -r ./node-agent/. "$AGENT_DIR/"
elif [[ -f agent.js ]]; then
  cp -r . "$AGENT_DIR/"
else
  echo "[x] Could not find the node-agent files. Run this script from the venlix-nodes repo root." >&2
  exit 1
fi

# ---------- write env ----------
AGENT_UPDATE_REPO="${AGENT_UPDATE_REPO:-https://github.com/rgdevil54321-afk/vm-panel-.git}"
AGENT_UPDATE_BRANCH="${AGENT_UPDATE_BRANCH:-main}"
# Generate a one-time join key so the panel can onboard this node by pasting a code.
JOIN_CODE="$(cat /dev/urandom | tr -dc 'A-Z0-9' | head -c 12 | sed 's/.\{4\}/&-/g' | sed 's/-$//')"
cat > "$AGENT_DIR/.env" <<EOF
AGENT_PORT=3005
AGENT_HOST=0.0.0.0
AGENT_TOKEN=$AGENT_TOKEN
AGENT_JOIN_CODE=$JOIN_CODE
AGENT_UPDATE_REPO=$AGENT_UPDATE_REPO
AGENT_UPDATE_BRANCH=$AGENT_UPDATE_BRANCH
NO_KVM=
EOF

# Create state + vm dirs
mkdir -p "$AGENT_DIR/data" "$AGENT_DIR/vms"

echo "[+] Installing Node dependencies (uuid only)..."
cd "$AGENT_DIR"
# uuid is the only third-party dependency (no native build)
npm install uuid --save
if [[ ! -d node_modules ]]; then
  echo "[x] npm install failed. Check network access." >&2
  exit 1
fi

# ---------- set node metadata ----------
cat > /tmp/venlix-meta.json <<EOF
{"name":"$NODE_NAME"}
EOF
AGENT_TOKEN="$AGENT_TOKEN" node -e "require('dotenv')" 2>/dev/null || true
# simplest: store name via env on first boot; agent reads AGENT_NODE_NAME
echo "AGENT_NODE_NAME=$NODE_NAME" >> "$AGENT_DIR/.env"

# ---------- systemd unit ----------
echo "[+] Creating systemd service..."
cat > /etc/systemd/system/venlix-node.service <<EOF
[Unit]
Description=Venlix Nodes - Node Agent (QEMU VM Hypervisor)
After=network.target

[Service]
Type=simple
WorkingDirectory=$AGENT_DIR
EnvironmentFile=$AGENT_DIR/.env
ExecStart=/usr/bin/node $AGENT_DIR/agent.js
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable venlix-node
systemctl restart venlix-node || true

# Resolve the address the PANEL must use to reach this node.
# Prefer the PUBLIC IP (works when the panel is on another VPS / Codesandbox),
# because `hostname -I` inside containers yields unroutable bridge IPs (172.17.x.x).
echo "[+] Detecting the public/reachable address for this node..."
PUB_IP="$(curl -s -m 5 -4 https://api.ipify.org 2>/dev/null || curl -s -m 5 ifconfig.me 2>/dev/null || echo '')"
if [[ -z "$PUB_IP" ]]; then
  echo "    [!] Could not auto-detect public IP; falling back to network address."
  PUB_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
fi
if [[ -z "$PUB_IP" ]]; then
  PUB_IP="<this-server-ip>"
fi

echo ""
echo "  This node is reachable by the panel via:  $PUB_IP"
read -r -p "  Enter the address the panel should use (or press Enter to keep [$PUB_IP]): " NODE_HOST
NODE_HOST="${NODE_HOST:-$PUB_IP}"

echo ""
echo "============================================="
echo "  Node agent installed — CONNECT WITH KEY"
echo "============================================="
echo ""
echo "  Node name : $NODE_NAME"
echo ""
echo "  >>> Connect Key <<<"
echo ""
echo "      ${JOIN_CODE}@${NODE_HOST}:3005"
echo ""
echo "  On your panel:"
echo "    1. Go to Nodes & Cluster Overview"
echo "    2. Click 'Connect With Node Key'"
echo "    3. Paste the Connect Key above"
echo "    -> Your node connects automatically."
echo ""
echo "  (Port 3005 must be reachable from the panel via the firewall.)"
echo "============================================="
